# Generated by Django 5.2 on 2025-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscribers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
